<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2005

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce 2005 Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:include href="Apriso_Functions.xsl"/>
	<xsl:template match="/MATMAS05">
		<FlexNet_Products>
			
			<xsl:attribute name="Version">
				<xsl:value-of select="'1.0'"/>
			</xsl:attribute>
			<xsl:for-each select="IDOC">
				<xsl:for-each select="E1MARAM">
					<xsl:for-each select="MEINS">
						<Uom>
							<UomCode>
								<xsl:value-of select="."/>
							</UomCode>
						</Uom>
					</xsl:for-each>
				</xsl:for-each>
			</xsl:for-each>
			<xsl:for-each select="IDOC">
				<xsl:for-each select="E1MARAM">
					<xsl:for-each select="MTART">
						<Group>
							<Group>
								<xsl:value-of select="."/>
							</Group>
							<GroupType>
								<xsl:value-of select="'2'"/>
							</GroupType>
							<GroupClassID>
								<xsl:value-of select="'1'"/>
							</GroupClassID>
						</Group>
					</xsl:for-each>
				</xsl:for-each>
			</xsl:for-each>
			<xsl:for-each select="IDOC">
				<xsl:for-each select="E1MARAM">
					<xsl:variable name="E1MARAM" select="."/>
					<Product>
						<xsl:for-each select="MATNR">
							<xsl:variable name="MATNR" select="."/>
							<xsl:variable name="StripLeadingZerosResult">
								<xsl:call-template name="StripLeadingZeros">
									<xsl:with-param name="NumberWithZeros" select="$MATNR"/>
								</xsl:call-template>
							</xsl:variable>
							<ProductNo>
								<xsl:value-of select="$StripLeadingZerosResult"/>
							</ProductNo>
						</xsl:for-each>
						<LotTrackingCode>
							<xsl:value-of select="'0'"/>
						</LotTrackingCode>
						<SerialTrackingCode>
							<xsl:value-of select="'0'"/>
						</SerialTrackingCode>
						<FractionAllowed>
							<xsl:value-of select="'0'"/>
						</FractionAllowed>
						<RevisionControlFlag>
							<xsl:value-of select="'0'"/>
						</RevisionControlFlag>
						<xsl:for-each select="MEINS">
							<DefaultUomCode>
								<xsl:value-of select="."/>
							</DefaultUomCode>
						</xsl:for-each>
						<xsl:for-each select="MTART">
							<xsl:variable name="MTART" select="."/>
							<xsl:variable name="SAPProductInventoryTypeConversionResult">
								<xsl:call-template name="SAPProductInventoryTypeConversion">
									<xsl:with-param name="MaterialType" select="$MTART"/>
								</xsl:call-template>
							</xsl:variable>
							<ProductInventoryType>
								<xsl:value-of select="$SAPProductInventoryTypeConversionResult"/>
							</ProductInventoryType>
						</xsl:for-each>
						<xsl:for-each select="LVORM">
							<xsl:variable name="LVORM" select="."/>
							<xsl:variable name="ComparisonResult" select="$LVORM = 'X'"/>
							<Active>
								<xsl:variable name="ConditionResult">
									<xsl:choose>
										<xsl:when test="string($ComparisonResult)='true'">
											<xsl:value-of select="'0'"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="'1'"/>
										</xsl:otherwise>
									</xsl:choose>
								</xsl:variable>
								<xsl:value-of select="$ConditionResult"/>
							</Active>
						</xsl:for-each>
						<xsl:for-each select="E1MAKTM">
							<xsl:variable name="E1MAKTM" select="."/>
							<xsl:for-each select="MAKTX">
								<xsl:variable name="MAKTX" select="."/>
								<xsl:for-each select="$E1MAKTM/SPRAS_ISO">
									<xsl:variable name="SPRAS_ISO" select="."/>
									<xsl:variable name="SAPLanguageIDConversionResult">
										<xsl:call-template name="SAPLanguageIDConversion">
											<xsl:with-param name="SPRAS_ISO" select="$SPRAS_ISO"/>
										</xsl:call-template>
									</xsl:variable>
									<xsl:variable name="ComparisonResult1" select="$SAPLanguageIDConversionResult = '1033'"/>
									<xsl:if test="string($ComparisonResult1)='true'">
										<Medium>
											<xsl:value-of select="$MAKTX"/>
										</Medium>
									</xsl:if>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<TextID>
							<Text>
								<Active>
									<xsl:value-of select="'1'"/>
								</Active>
							</Text>
						</TextID>
						<ProductUom>
							<xsl:for-each select="MEINS">
								<UomCode>
									<xsl:value-of select="."/>
								</UomCode>
							</xsl:for-each>
							<StockingFlag>
								<xsl:value-of select="'0'"/>
							</StockingFlag>
							<ProductID>
								<xsl:attribute name="NodeType">
									<xsl:value-of select="'Field'"/>
								</xsl:attribute>
							</ProductID>
						</ProductUom>
						<xsl:for-each select="E1MARMM">
							<xsl:variable name="E1MARMM" select="."/>
							<xsl:for-each select="MEINH">
								<xsl:variable name="MEINH" select="."/>
								<xsl:for-each select="$E1MARAM/MEINS">
									<xsl:variable name="MEINS" select="."/>
									<xsl:variable name="ComparisonResult2" select="$MEINH = $MEINS"/>
									<xsl:variable name="ComparisonResult3" select="$ComparisonResult2 = 'false'"/>
									<xsl:if test="string($ComparisonResult3)='true'">
										<ProductUomConversion>
											<xsl:for-each select="$E1MARMM/MEINH">
												<UomCodeFrom>
													<xsl:value-of select="."/>
												</UomCodeFrom>
											</xsl:for-each>
											<UomCodeTo>
												<xsl:value-of select="."/>
											</UomCodeTo>
											<xsl:for-each select="$E1MARMM/UMREZ">
												<xsl:variable name="UMREZ" select="."/>
												<xsl:for-each select="$E1MARMM/UMREN">
													<xsl:variable name="UMREN" select="."/>
													<xsl:variable name="DivisionResult" select="$UMREZ div $UMREN"/>
													<ConversionFactor>
														<xsl:value-of select="$DivisionResult"/>
													</ConversionFactor>
												</xsl:for-each>
											</xsl:for-each>
											<ProductID>
												<xsl:attribute name="NodeType">
													<xsl:value-of select="'Field'"/>
												</xsl:attribute>
											</ProductID>
										</ProductUomConversion>
									</xsl:if>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="E1MARCM">
							<xsl:variable name="VEXISTS">
								<xsl:variable name="ExistsResult">
									<xsl:for-each select="XCHPF">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult1">
								<xsl:choose>
									<xsl:when test="string($VEXISTS)='true'">
										<xsl:for-each select="XCHPF">
											<xsl:variable name="XCHPF" select="."/>
											<xsl:value-of select="$XCHPF"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS1">
								<xsl:variable name="ExistsResult1">
									<xsl:for-each select="SERNP">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult1='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult2">
								<xsl:choose>
									<xsl:when test="string($VEXISTS1)='true'">
										<xsl:for-each select="SERNP">
											<xsl:variable name="SERNP" select="."/>
											<xsl:value-of select="$SERNP"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS2">
								<xsl:variable name="ExistsResult2">
									<xsl:for-each select="INSMK">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult2='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult3">
								<xsl:choose>
									<xsl:when test="string($VEXISTS2)='true'">
										<xsl:for-each select="INSMK">
											<xsl:variable name="INSMK" select="."/>
											<xsl:value-of select="$INSMK"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="GetLotSerialTrackResult">
								<xsl:call-template name="GetLotSerialTrack">
									<xsl:with-param name="XCHPF" select="$ConditionResult1"/>
									<xsl:with-param name="SERNP" select="$ConditionResult2"/>
									<xsl:with-param name="INSMK" select="$ConditionResult3"/>
								</xsl:call-template>
							</xsl:variable>
							<xsl:variable name="ComparisonResult4" select="$GetLotSerialTrackResult = '0'"/>
							<xsl:if test="string($ComparisonResult4)='true'">
								<ProductFacility>
									<xsl:for-each select="WERKS">
										<Facility>
											<xsl:value-of select="."/>
										</Facility>
									</xsl:for-each>
									<LotTrackingCode>
										<xsl:value-of select="'0'"/>
									</LotTrackingCode>
									<SerialTrackingCode>
										<xsl:value-of select="'0'"/>
									</SerialTrackingCode>
									<InspectionRequired>
										<xsl:value-of select="'0'"/>
									</InspectionRequired>
									<ProductID>
										<xsl:attribute name="NodeType">
											<xsl:value-of select="'Field'"/>
										</xsl:attribute>
									</ProductID>
								</ProductFacility>
							</xsl:if>
						</xsl:for-each>
						<xsl:for-each select="E1MARCM">
							<xsl:variable name="VEXISTS3">
								<xsl:variable name="ExistsResult3">
									<xsl:for-each select="XCHPF">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult3='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult4">
								<xsl:choose>
									<xsl:when test="string($VEXISTS3)='true'">
										<xsl:for-each select="XCHPF">
											<xsl:variable name="XCHPF1" select="."/>
											<xsl:value-of select="$XCHPF1"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS4">
								<xsl:variable name="ExistsResult4">
									<xsl:for-each select="SERNP">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult4='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult5">
								<xsl:choose>
									<xsl:when test="string($VEXISTS4)='true'">
										<xsl:for-each select="SERNP">
											<xsl:variable name="SERNP1" select="."/>
											<xsl:value-of select="$SERNP1"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS5">
								<xsl:variable name="ExistsResult5">
									<xsl:for-each select="INSMK">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult5='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult6">
								<xsl:choose>
									<xsl:when test="string($VEXISTS5)='true'">
										<xsl:for-each select="INSMK">
											<xsl:variable name="INSMK1" select="."/>
											<xsl:value-of select="$INSMK1"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="GetLotSerialTrackResult1">
								<xsl:call-template name="GetLotSerialTrack">
									<xsl:with-param name="XCHPF" select="$ConditionResult4"/>
									<xsl:with-param name="SERNP" select="$ConditionResult5"/>
									<xsl:with-param name="INSMK" select="$ConditionResult6"/>
								</xsl:call-template>
							</xsl:variable>
							<xsl:variable name="ComparisonResult5" select="$GetLotSerialTrackResult1 = '1'"/>
							<xsl:if test="string($ComparisonResult5)='true'">
								<ProductFacility>
									<xsl:for-each select="WERKS">
										<Facility>
											<xsl:value-of select="."/>
										</Facility>
									</xsl:for-each>
									<xsl:variable name="VEXISTS6">
										<xsl:variable name="ExistsResult6">
											<xsl:for-each select="XCHPF">
												<xsl:value-of select="true()"/>
											</xsl:for-each>
										</xsl:variable>
										<xsl:choose>
											<xsl:when test="$ExistsResult6='true'">
												<xsl:value-of select="'true'"/>
											</xsl:when>
											<xsl:otherwise>
												<xsl:value-of select="'false'"/>
											</xsl:otherwise>
										</xsl:choose>
									</xsl:variable>
									<FacilityProdStatus>
										<xsl:variable name="ConditionResult7">
											<xsl:choose>
												<xsl:when test="string($VEXISTS6)='true'">
													<xsl:for-each select="XCHPF">
														<xsl:variable name="XCHPF2" select="."/>
														<xsl:value-of select="$XCHPF2"/>
													</xsl:for-each>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="''"/>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:variable>
										<xsl:variable name="VEXISTS7">
											<xsl:variable name="ExistsResult7">
												<xsl:for-each select="SERNP">
													<xsl:value-of select="true()"/>
												</xsl:for-each>
											</xsl:variable>
											<xsl:choose>
												<xsl:when test="$ExistsResult7='true'">
													<xsl:value-of select="'true'"/>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="'false'"/>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:variable>
										<xsl:variable name="ConditionResult8">
											<xsl:choose>
												<xsl:when test="string($VEXISTS7)='true'">
													<xsl:for-each select="SERNP">
														<xsl:variable name="SERNP2" select="."/>
														<xsl:value-of select="$SERNP2"/>
													</xsl:for-each>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="''"/>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:variable>
										<xsl:variable name="VEXISTS8">
											<xsl:variable name="ExistsResult8">
												<xsl:for-each select="INSMK">
													<xsl:value-of select="true()"/>
												</xsl:for-each>
											</xsl:variable>
											<xsl:choose>
												<xsl:when test="$ExistsResult8='true'">
													<xsl:value-of select="'true'"/>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="'false'"/>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:variable>
										<xsl:variable name="ConditionResult9">
											<xsl:choose>
												<xsl:when test="string($VEXISTS8)='true'">
													<xsl:for-each select="INSMK">
														<xsl:variable name="INSMK2" select="."/>
														<xsl:value-of select="$INSMK2"/>
													</xsl:for-each>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="''"/>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:variable>
										<xsl:variable name="GetLotSerialTrackResult2">
											<xsl:call-template name="GetLotSerialTrack">
												<xsl:with-param name="XCHPF" select="$ConditionResult7"/>
												<xsl:with-param name="SERNP" select="$ConditionResult8"/>
												<xsl:with-param name="INSMK" select="$ConditionResult9"/>
											</xsl:call-template>
										</xsl:variable>
										<xsl:value-of select="$GetLotSerialTrackResult2"/>
									</FacilityProdStatus>
									<LotTrackingCode>
										<xsl:value-of select="'4'"/>
									</LotTrackingCode>
									<SerialTrackingCode>
										<xsl:value-of select="'0'"/>
									</SerialTrackingCode>
									<InspectionRequired>
										<xsl:value-of select="'0'"/>
									</InspectionRequired>
									<ProductID>
										<xsl:attribute name="NodeType">
											<xsl:value-of select="'Field'"/>
										</xsl:attribute>
									</ProductID>
								</ProductFacility>
							</xsl:if>
						</xsl:for-each>
						<xsl:for-each select="E1MARCM">
							<xsl:variable name="VEXISTS9">
								<xsl:variable name="ExistsResult9">
									<xsl:for-each select="XCHPF">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult9='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult10">
								<xsl:choose>
									<xsl:when test="string($VEXISTS9)='true'">
										<xsl:for-each select="XCHPF">
											<xsl:variable name="XCHPF3" select="."/>
											<xsl:value-of select="$XCHPF3"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS10">
								<xsl:variable name="ExistsResult10">
									<xsl:for-each select="SERNP">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult10='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult11">
								<xsl:choose>
									<xsl:when test="string($VEXISTS10)='true'">
										<xsl:for-each select="SERNP">
											<xsl:variable name="SERNP3" select="."/>
											<xsl:value-of select="$SERNP3"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS11">
								<xsl:variable name="ExistsResult11">
									<xsl:for-each select="INSMK">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult11='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult12">
								<xsl:choose>
									<xsl:when test="string($VEXISTS11)='true'">
										<xsl:for-each select="INSMK">
											<xsl:variable name="INSMK3" select="."/>
											<xsl:value-of select="$INSMK3"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="GetLotSerialTrackResult3">
								<xsl:call-template name="GetLotSerialTrack">
									<xsl:with-param name="XCHPF" select="$ConditionResult10"/>
									<xsl:with-param name="SERNP" select="$ConditionResult11"/>
									<xsl:with-param name="INSMK" select="$ConditionResult12"/>
								</xsl:call-template>
							</xsl:variable>
							<xsl:variable name="ComparisonResult6" select="$GetLotSerialTrackResult3 = '3'"/>
							<xsl:if test="string($ComparisonResult6)='true'">
								<ProductFacility>
									<xsl:for-each select="WERKS">
										<Facility>
											<xsl:value-of select="."/>
										</Facility>
									</xsl:for-each>
									<xsl:variable name="VEXISTS12">
										<xsl:variable name="ExistsResult12">
											<xsl:for-each select="XCHPF">
												<xsl:value-of select="true()"/>
											</xsl:for-each>
										</xsl:variable>
										<xsl:choose>
											<xsl:when test="$ExistsResult12='true'">
												<xsl:value-of select="'true'"/>
											</xsl:when>
											<xsl:otherwise>
												<xsl:value-of select="'false'"/>
											</xsl:otherwise>
										</xsl:choose>
									</xsl:variable>
									<FacilityProdStatus>
										<xsl:variable name="ConditionResult13">
											<xsl:choose>
												<xsl:when test="string($VEXISTS12)='true'">
													<xsl:for-each select="XCHPF">
														<xsl:variable name="XCHPF4" select="."/>
														<xsl:value-of select="$XCHPF4"/>
													</xsl:for-each>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="''"/>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:variable>
										<xsl:variable name="VEXISTS13">
											<xsl:variable name="ExistsResult13">
												<xsl:for-each select="SERNP">
													<xsl:value-of select="true()"/>
												</xsl:for-each>
											</xsl:variable>
											<xsl:choose>
												<xsl:when test="$ExistsResult13='true'">
													<xsl:value-of select="'true'"/>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="'false'"/>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:variable>
										<xsl:variable name="ConditionResult14">
											<xsl:choose>
												<xsl:when test="string($VEXISTS13)='true'">
													<xsl:for-each select="SERNP">
														<xsl:variable name="SERNP4" select="."/>
														<xsl:value-of select="$SERNP4"/>
													</xsl:for-each>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="''"/>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:variable>
										<xsl:variable name="VEXISTS14">
											<xsl:variable name="ExistsResult14">
												<xsl:for-each select="INSMK">
													<xsl:value-of select="true()"/>
												</xsl:for-each>
											</xsl:variable>
											<xsl:choose>
												<xsl:when test="$ExistsResult14='true'">
													<xsl:value-of select="'true'"/>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="'false'"/>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:variable>
										<xsl:variable name="ConditionResult15">
											<xsl:choose>
												<xsl:when test="string($VEXISTS14)='true'">
													<xsl:for-each select="INSMK">
														<xsl:variable name="INSMK4" select="."/>
														<xsl:value-of select="$INSMK4"/>
													</xsl:for-each>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="''"/>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:variable>
										<xsl:variable name="GetLotSerialTrackResult4">
											<xsl:call-template name="GetLotSerialTrack">
												<xsl:with-param name="XCHPF" select="$ConditionResult13"/>
												<xsl:with-param name="SERNP" select="$ConditionResult14"/>
												<xsl:with-param name="INSMK" select="$ConditionResult15"/>
											</xsl:call-template>
										</xsl:variable>
										<xsl:value-of select="$GetLotSerialTrackResult4"/>
									</FacilityProdStatus>
									<LotTrackingCode>
										<xsl:value-of select="'0'"/>
									</LotTrackingCode>
									<SerialTrackingCode>
										<xsl:value-of select="'4'"/>
									</SerialTrackingCode>
									<InspectionRequired>
										<xsl:value-of select="'0'"/>
									</InspectionRequired>
									<ProductID>
										<xsl:attribute name="NodeType">
											<xsl:value-of select="'Field'"/>
										</xsl:attribute>
									</ProductID>
								</ProductFacility>
							</xsl:if>
						</xsl:for-each>
						<xsl:for-each select="E1MARCM">
							<xsl:variable name="VEXISTS15">
								<xsl:variable name="ExistsResult15">
									<xsl:for-each select="XCHPF">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult15='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult16">
								<xsl:choose>
									<xsl:when test="string($VEXISTS15)='true'">
										<xsl:for-each select="XCHPF">
											<xsl:variable name="XCHPF5" select="."/>
											<xsl:value-of select="$XCHPF5"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS16">
								<xsl:variable name="ExistsResult16">
									<xsl:for-each select="SERNP">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult16='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult17">
								<xsl:choose>
									<xsl:when test="string($VEXISTS16)='true'">
										<xsl:for-each select="SERNP">
											<xsl:variable name="SERNP5" select="."/>
											<xsl:value-of select="$SERNP5"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS17">
								<xsl:variable name="ExistsResult17">
									<xsl:for-each select="INSMK">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult17='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult18">
								<xsl:choose>
									<xsl:when test="string($VEXISTS17)='true'">
										<xsl:for-each select="INSMK">
											<xsl:variable name="INSMK5" select="."/>
											<xsl:value-of select="$INSMK5"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="GetLotSerialTrackResult5">
								<xsl:call-template name="GetLotSerialTrack">
									<xsl:with-param name="XCHPF" select="$ConditionResult16"/>
									<xsl:with-param name="SERNP" select="$ConditionResult17"/>
									<xsl:with-param name="INSMK" select="$ConditionResult18"/>
								</xsl:call-template>
							</xsl:variable>
							<xsl:variable name="ComparisonResult7" select="$GetLotSerialTrackResult5 = '4'"/>
							<xsl:if test="string($ComparisonResult7)='true'">
								<ProductFacility>
									<xsl:for-each select="WERKS">
										<Facility>
											<xsl:value-of select="."/>
										</Facility>
									</xsl:for-each>
									<LotTrackingCode>
										<xsl:value-of select="'4'"/>
									</LotTrackingCode>
									<SerialTrackingCode>
										<xsl:value-of select="'4'"/>
									</SerialTrackingCode>
									<InspectionRequired>
										<xsl:value-of select="'0'"/>
									</InspectionRequired>
									<ProductID>
										<xsl:attribute name="NodeType">
											<xsl:value-of select="'Field'"/>
										</xsl:attribute>
									</ProductID>
								</ProductFacility>
							</xsl:if>
						</xsl:for-each>
						<xsl:for-each select="E1MARCM">
							<xsl:variable name="VEXISTS18">
								<xsl:variable name="ExistsResult18">
									<xsl:for-each select="XCHPF">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult18='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult19">
								<xsl:choose>
									<xsl:when test="string($VEXISTS18)='true'">
										<xsl:for-each select="XCHPF">
											<xsl:variable name="XCHPF6" select="."/>
											<xsl:value-of select="$XCHPF6"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS19">
								<xsl:variable name="ExistsResult19">
									<xsl:for-each select="SERNP">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult19='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult20">
								<xsl:choose>
									<xsl:when test="string($VEXISTS19)='true'">
										<xsl:for-each select="SERNP">
											<xsl:variable name="SERNP6" select="."/>
											<xsl:value-of select="$SERNP6"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS20">
								<xsl:variable name="ExistsResult20">
									<xsl:for-each select="INSMK">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult20='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult21">
								<xsl:choose>
									<xsl:when test="string($VEXISTS20)='true'">
										<xsl:for-each select="INSMK">
											<xsl:variable name="INSMK6" select="."/>
											<xsl:value-of select="$INSMK6"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="GetLotSerialTrackResult6">
								<xsl:call-template name="GetLotSerialTrack">
									<xsl:with-param name="XCHPF" select="$ConditionResult19"/>
									<xsl:with-param name="SERNP" select="$ConditionResult20"/>
									<xsl:with-param name="INSMK" select="$ConditionResult21"/>
								</xsl:call-template>
							</xsl:variable>
							<xsl:variable name="ComparisonResult8" select="$GetLotSerialTrackResult6 = '5'"/>
							<xsl:if test="string($ComparisonResult8)='true'">
								<ProductFacility>
									<xsl:for-each select="WERKS">
										<Facility>
											<xsl:value-of select="."/>
										</Facility>
									</xsl:for-each>
									<LotTrackingCode>
										<xsl:value-of select="'0'"/>
									</LotTrackingCode>
									<SerialTrackingCode>
										<xsl:value-of select="'0'"/>
									</SerialTrackingCode>
									<InspectionRequired>
										<xsl:value-of select="'1'"/>
									</InspectionRequired>
									<ProductID>
										<xsl:attribute name="NodeType">
											<xsl:value-of select="'Field'"/>
										</xsl:attribute>
									</ProductID>
								</ProductFacility>
							</xsl:if>
						</xsl:for-each>
						<xsl:for-each select="E1MARCM">
							<xsl:variable name="VEXISTS21">
								<xsl:variable name="ExistsResult21">
									<xsl:for-each select="XCHPF">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult21='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult22">
								<xsl:choose>
									<xsl:when test="string($VEXISTS21)='true'">
										<xsl:for-each select="XCHPF">
											<xsl:variable name="XCHPF7" select="."/>
											<xsl:value-of select="$XCHPF7"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS22">
								<xsl:variable name="ExistsResult22">
									<xsl:for-each select="SERNP">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult22='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult23">
								<xsl:choose>
									<xsl:when test="string($VEXISTS22)='true'">
										<xsl:for-each select="SERNP">
											<xsl:variable name="SERNP7" select="."/>
											<xsl:value-of select="$SERNP7"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS23">
								<xsl:variable name="ExistsResult23">
									<xsl:for-each select="INSMK">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult23='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult24">
								<xsl:choose>
									<xsl:when test="string($VEXISTS23)='true'">
										<xsl:for-each select="INSMK">
											<xsl:variable name="INSMK7" select="."/>
											<xsl:value-of select="$INSMK7"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="GetLotSerialTrackResult7">
								<xsl:call-template name="GetLotSerialTrack">
									<xsl:with-param name="XCHPF" select="$ConditionResult22"/>
									<xsl:with-param name="SERNP" select="$ConditionResult23"/>
									<xsl:with-param name="INSMK" select="$ConditionResult24"/>
								</xsl:call-template>
							</xsl:variable>
							<xsl:variable name="ComparisonResult9" select="$GetLotSerialTrackResult7 = '8'"/>
							<xsl:if test="string($ComparisonResult9)='true'">
								<ProductFacility>
									<xsl:for-each select="WERKS">
										<Facility>
											<xsl:value-of select="."/>
										</Facility>
									</xsl:for-each>
									<LotTrackingCode>
										<xsl:value-of select="'0'"/>
									</LotTrackingCode>
									<SerialTrackingCode>
										<xsl:value-of select="'4'"/>
									</SerialTrackingCode>
									<InspectionRequired>
										<xsl:value-of select="'1'"/>
									</InspectionRequired>
									<ProductID>
										<xsl:attribute name="NodeType">
											<xsl:value-of select="'Field'"/>
										</xsl:attribute>
									</ProductID>
								</ProductFacility>
							</xsl:if>
						</xsl:for-each>
						<xsl:for-each select="E1MARCM">
							<xsl:variable name="VEXISTS24">
								<xsl:variable name="ExistsResult24">
									<xsl:for-each select="XCHPF">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult24='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult25">
								<xsl:choose>
									<xsl:when test="string($VEXISTS24)='true'">
										<xsl:for-each select="XCHPF">
											<xsl:variable name="XCHPF8" select="."/>
											<xsl:value-of select="$XCHPF8"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS25">
								<xsl:variable name="ExistsResult25">
									<xsl:for-each select="SERNP">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult25='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult26">
								<xsl:choose>
									<xsl:when test="string($VEXISTS25)='true'">
										<xsl:for-each select="SERNP">
											<xsl:variable name="SERNP8" select="."/>
											<xsl:value-of select="$SERNP8"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="VEXISTS26">
								<xsl:variable name="ExistsResult26">
									<xsl:for-each select="INSMK">
										<xsl:value-of select="true()"/>
									</xsl:for-each>
								</xsl:variable>
								<xsl:choose>
									<xsl:when test="$ExistsResult26='true'">
										<xsl:value-of select="'true'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="'false'"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="ConditionResult27">
								<xsl:choose>
									<xsl:when test="string($VEXISTS26)='true'">
										<xsl:for-each select="INSMK">
											<xsl:variable name="INSMK8" select="."/>
											<xsl:value-of select="$INSMK8"/>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="''"/>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="GetLotSerialTrackResult8">
								<xsl:call-template name="GetLotSerialTrack">
									<xsl:with-param name="XCHPF" select="$ConditionResult25"/>
									<xsl:with-param name="SERNP" select="$ConditionResult26"/>
									<xsl:with-param name="INSMK" select="$ConditionResult27"/>
								</xsl:call-template>
							</xsl:variable>
							<xsl:variable name="ComparisonResult10" select="$GetLotSerialTrackResult8 = '9'"/>
							<xsl:if test="string($ComparisonResult10)='true'">
								<ProductFacility>
									<xsl:for-each select="WERKS">
										<Facility>
											<xsl:value-of select="."/>
										</Facility>
									</xsl:for-each>
									<LotTrackingCode>
										<xsl:value-of select="'4'"/>
									</LotTrackingCode>
									<SerialTrackingCode>
										<xsl:value-of select="'4'"/>
									</SerialTrackingCode>
									<InspectionRequired>
										<xsl:value-of select="'1'"/>
									</InspectionRequired>
									<ProductID>
										<xsl:attribute name="NodeType">
											<xsl:value-of select="'Field'"/>
										</xsl:attribute>
									</ProductID>
								</ProductFacility>
							</xsl:if>
						</xsl:for-each>
						<ProductGroup>
							<xsl:for-each select="MTART">
								<Group>
									<xsl:value-of select="."/>
								</Group>
							</xsl:for-each>
							<GroupType>
								<xsl:value-of select="'2'"/>
							</GroupType>
							<GroupClassID>
								<xsl:value-of select="'1'"/>
							</GroupClassID>
							<ProductID>
								<xsl:attribute name="NodeType">
									<xsl:value-of select="'Field'"/>
								</xsl:attribute>
							</ProductID>
						</ProductGroup>
						<xsl:for-each select="E1MBEWM">
							<ProductCost>
								<xsl:for-each select="STPRS">
									<UnitCost>
										<xsl:value-of select="."/>
									</UnitCost>
								</xsl:for-each>
								<ProductID>
									<xsl:attribute name="NodeType">
										<xsl:value-of select="'Field'"/>
									</xsl:attribute>
								</ProductID>
							</ProductCost>
						</xsl:for-each>
						<ProductDimension>
							<xsl:for-each select="NTGEW">
								<xsl:variable name="NTGEW" select="."/>
								<xsl:variable name="string-lengthResult" select="string-length($NTGEW)"/>
								<xsl:variable name="ComparisonResult11" select="$string-lengthResult &gt; '0'"/>
								<DimensionCode>
									<xsl:variable name="ConditionResult28">
										<xsl:choose>
											<xsl:when test="string($ComparisonResult11)='true'">
												<xsl:value-of select="'UnitNetWeight'"/>
											</xsl:when>
											<xsl:otherwise/>
										</xsl:choose>
									</xsl:variable>
									<xsl:value-of select="$ConditionResult28"/>
								</DimensionCode>
							</xsl:for-each>
							<xsl:for-each select="NTGEW">
								<xsl:variable name="NTGEW1" select="."/>
								<xsl:variable name="string-lengthResult1" select="string-length($NTGEW1)"/>
								<xsl:variable name="ComparisonResult12" select="$string-lengthResult1 &gt; '0'"/>
								<AverageValue>
									<xsl:variable name="ConditionResult29">
										<xsl:choose>
											<xsl:when test="string($ComparisonResult12)='true'">
												<xsl:variable name="NTGEW2" select="."/>
												<xsl:value-of select="$NTGEW2"/>
											</xsl:when>
											<xsl:otherwise/>
										</xsl:choose>
									</xsl:variable>
									<xsl:value-of select="$ConditionResult29"/>
								</AverageValue>
							</xsl:for-each>
							<xsl:for-each select="NTGEW">
								<xsl:variable name="NTGEW3" select="."/>
								<xsl:variable name="string-lengthResult2" select="string-length($NTGEW3)"/>
								<xsl:variable name="ComparisonResult13" select="$string-lengthResult2 &gt; '0'"/>
								<UomCode>
									<xsl:variable name="ConditionResult30">
										<xsl:choose>
											<xsl:when test="string($ComparisonResult13)='true'">
												<xsl:for-each select="$E1MARAM/GEWEI">
													<xsl:variable name="GEWEI" select="."/>
													<xsl:value-of select="$GEWEI"/>
												</xsl:for-each>
											</xsl:when>
											<xsl:otherwise/>
										</xsl:choose>
									</xsl:variable>
									<xsl:value-of select="$ConditionResult30"/>
								</UomCode>
							</xsl:for-each>
							<ProductID>
								<xsl:attribute name="NodeType">
									<xsl:value-of select="'Field'"/>
								</xsl:attribute>
							</ProductID>
						</ProductDimension>
						<ProductDimension>
							<xsl:for-each select="BREIT">
								<xsl:variable name="BREIT" select="."/>
								<xsl:variable name="string-lengthResult3" select="string-length($BREIT)"/>
								<xsl:variable name="ComparisonResult14" select="$string-lengthResult3 &gt; '0'"/>
								<DimensionCode>
									<xsl:variable name="ConditionResult31">
										<xsl:choose>
											<xsl:when test="string($ComparisonResult14)='true'">
												<xsl:value-of select="'WidthDimension'"/>
											</xsl:when>
											<xsl:otherwise/>
										</xsl:choose>
									</xsl:variable>
									<xsl:value-of select="$ConditionResult31"/>
								</DimensionCode>
							</xsl:for-each>
							<xsl:for-each select="BREIT">
								<xsl:variable name="BREIT1" select="."/>
								<xsl:variable name="string-lengthResult4" select="string-length($BREIT1)"/>
								<xsl:variable name="ComparisonResult15" select="$string-lengthResult4 &gt; '0'"/>
								<AverageValue>
									<xsl:variable name="ConditionResult32">
										<xsl:choose>
											<xsl:when test="string($ComparisonResult15)='true'">
												<xsl:variable name="BREIT2" select="."/>
												<xsl:value-of select="$BREIT2"/>
											</xsl:when>
											<xsl:otherwise/>
										</xsl:choose>
									</xsl:variable>
									<xsl:value-of select="$ConditionResult32"/>
								</AverageValue>
							</xsl:for-each>
							<ProductID>
								<xsl:attribute name="NodeType">
									<xsl:value-of select="'Field'"/>
								</xsl:attribute>
							</ProductID>
						</ProductDimension>
						<ProductDimension>
							<xsl:for-each select="LAENG">
								<xsl:variable name="LAENG" select="."/>
								<xsl:variable name="string-lengthResult5" select="string-length($LAENG)"/>
								<xsl:variable name="ComparisonResult16" select="$string-lengthResult5 &gt; '0'"/>
								<DimensionCode>
									<xsl:variable name="ConditionResult33">
										<xsl:choose>
											<xsl:when test="string($ComparisonResult16)='true'">
												<xsl:value-of select="'LengthDimension'"/>
											</xsl:when>
											<xsl:otherwise/>
										</xsl:choose>
									</xsl:variable>
									<xsl:value-of select="$ConditionResult33"/>
								</DimensionCode>
							</xsl:for-each>
							<xsl:for-each select="LAENG">
								<xsl:variable name="LAENG1" select="."/>
								<xsl:variable name="string-lengthResult6" select="string-length($LAENG1)"/>
								<xsl:variable name="ComparisonResult17" select="$string-lengthResult6 &gt; '0'"/>
								<AverageValue>
									<xsl:variable name="ConditionResult34">
										<xsl:choose>
											<xsl:when test="string($ComparisonResult17)='true'">
												<xsl:for-each select="$E1MARAM/BREIT">
													<xsl:variable name="BREIT3" select="."/>
													<xsl:value-of select="$BREIT3"/>
												</xsl:for-each>
											</xsl:when>
											<xsl:otherwise/>
										</xsl:choose>
									</xsl:variable>
									<xsl:value-of select="$ConditionResult34"/>
								</AverageValue>
							</xsl:for-each>
							<ProductID>
								<xsl:attribute name="NodeType">
									<xsl:value-of select="'Field'"/>
								</xsl:attribute>
							</ProductID>
						</ProductDimension>
						<ProductDimension>
							<xsl:for-each select="HOEHE">
								<xsl:variable name="HOEHE" select="."/>
								<xsl:variable name="string-lengthResult7" select="string-length($HOEHE)"/>
								<xsl:variable name="ComparisonResult18" select="$string-lengthResult7 &gt; '0'"/>
								<DimensionCode>
									<xsl:variable name="ConditionResult35">
										<xsl:choose>
											<xsl:when test="string($ComparisonResult18)='true'">
												<xsl:value-of select="'HeightDimension'"/>
											</xsl:when>
											<xsl:otherwise/>
										</xsl:choose>
									</xsl:variable>
									<xsl:value-of select="$ConditionResult35"/>
								</DimensionCode>
							</xsl:for-each>
							<xsl:for-each select="HOEHE">
								<xsl:variable name="HOEHE1" select="."/>
								<xsl:variable name="string-lengthResult8" select="string-length($HOEHE1)"/>
								<xsl:variable name="ComparisonResult19" select="$string-lengthResult8 &gt; '0'"/>
								<AverageValue>
									<xsl:variable name="ConditionResult36">
										<xsl:choose>
											<xsl:when test="string($ComparisonResult19)='true'">
												<xsl:variable name="HOEHE2" select="."/>
												<xsl:value-of select="$HOEHE2"/>
											</xsl:when>
											<xsl:otherwise/>
										</xsl:choose>
									</xsl:variable>
									<xsl:value-of select="$ConditionResult36"/>
								</AverageValue>
							</xsl:for-each>
							<ProductID>
								<xsl:attribute name="NodeType">
									<xsl:value-of select="'Field'"/>
								</xsl:attribute>
							</ProductID>
						</ProductDimension>
						<ProductDimension>
							<xsl:for-each select="BRGEW">
								<xsl:variable name="BRGEW" select="."/>
								<xsl:variable name="string-lengthResult9" select="string-length($BRGEW)"/>
								<xsl:variable name="ComparisonResult20" select="$string-lengthResult9 &gt; '0'"/>
								<DimensionCode>
									<xsl:variable name="ConditionResult37">
										<xsl:choose>
											<xsl:when test="string($ComparisonResult20)='true'">
												<xsl:value-of select="'UnitGrossWeight'"/>
											</xsl:when>
											<xsl:otherwise/>
										</xsl:choose>
									</xsl:variable>
									<xsl:value-of select="$ConditionResult37"/>
								</DimensionCode>
							</xsl:for-each>
							<xsl:for-each select="BRGEW">
								<xsl:variable name="BRGEW1" select="."/>
								<xsl:variable name="string-lengthResult10" select="string-length($BRGEW1)"/>
								<xsl:variable name="ComparisonResult21" select="$string-lengthResult10 &gt; '0'"/>
								<AverageValue>
									<xsl:variable name="ConditionResult38">
										<xsl:choose>
											<xsl:when test="string($ComparisonResult21)='true'">
												<xsl:variable name="BRGEW2" select="."/>
												<xsl:value-of select="$BRGEW2"/>
											</xsl:when>
											<xsl:otherwise/>
										</xsl:choose>
									</xsl:variable>
									<xsl:value-of select="$ConditionResult38"/>
								</AverageValue>
							</xsl:for-each>
							<ProductID>
								<xsl:attribute name="NodeType">
									<xsl:value-of select="'Field'"/>
								</xsl:attribute>
							</ProductID>
						</ProductDimension>
						<xsl:for-each select="E1MAKTM">
							<xsl:variable name="E1MAKTM1" select="."/>
							<xsl:for-each select="MAKTX">
								<xsl:for-each select="$E1MAKTM1/SPRAS_ISO">
									<xsl:variable name="SPRAS_ISO1" select="."/>
									<xsl:variable name="SAPLanguageIDConversionResult1">
										<xsl:call-template name="SAPLanguageIDConversion">
											<xsl:with-param name="SPRAS_ISO" select="$SPRAS_ISO1"/>
										</xsl:call-template>
									</xsl:variable>
									<xsl:variable name="ComparisonResult22" select="$SAPLanguageIDConversionResult1 = '1033'"/>
									<xsl:variable name="notResult" select="not($ComparisonResult22)"/>
									<xsl:if test="string($notResult)='true'">
										<Product_Text>
											<ID>
												<xsl:attribute name="NodeType">
													<xsl:value-of select="'Field'"/>
												</xsl:attribute>
											</ID>
											<xsl:for-each select="..">
												<xsl:variable name="E1MAKTM2" select="."/>
												<TextTranslation>
													<xsl:for-each select="SPRAS_ISO">
														<xsl:variable name="SPRAS_ISO2" select="."/>
														<xsl:variable name="SAPLanguageIDConversionResult2">
															<xsl:call-template name="SAPLanguageIDConversion">
																<xsl:with-param name="SPRAS_ISO" select="$SPRAS_ISO2"/>
															</xsl:call-template>
														</xsl:variable>
														<LanguageID>
															<xsl:value-of select="$SAPLanguageIDConversionResult2"/>
														</LanguageID>
													</xsl:for-each>
													<xsl:for-each select="MAKTX">
														<xsl:variable name="MAKTX1" select="."/>
														<xsl:for-each select="$E1MAKTM2/SPRAS_ISO">
															<xsl:variable name="SPRAS_ISO3" select="."/>
															<xsl:variable name="SAPLanguageIDConversionResult3">
																<xsl:call-template name="SAPLanguageIDConversion">
																	<xsl:with-param name="SPRAS_ISO" select="$SPRAS_ISO3"/>
																</xsl:call-template>
															</xsl:variable>
															<xsl:variable name="ComparisonResult23" select="$SAPLanguageIDConversionResult3 = '1033'"/>
															<xsl:variable name="notResult1" select="not($ComparisonResult23)"/>
															<xsl:if test="string($notResult1)='true'">
																<Medium>
																	<xsl:value-of select="$MAKTX1"/>
																</Medium>
															</xsl:if>
														</xsl:for-each>
													</xsl:for-each>
													<TextID>
														<xsl:attribute name="NodeType">
															<xsl:value-of select="'Field'"/>
														</xsl:attribute>
													</TextID>
												</TextTranslation>
											</xsl:for-each>
										</Product_Text>
									</xsl:if>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="E1MTXHM">
							<xsl:variable name="E1MTXHM" select="."/>
							<xsl:for-each select="E1MTXLM">
								<xsl:variable name="E1MTXLM" select="."/>
								<xsl:for-each select="TDLINE">
									<xsl:for-each select="$E1MTXHM/TDOBJECT">
										<xsl:variable name="TDOBJECT" select="."/>
										<xsl:variable name="ComparisonResult24" select="$TDOBJECT = 'MATERIAL'"/>
										<xsl:if test="string($ComparisonResult24)='true'">
											<Product_Text>
												<ID>
													<xsl:attribute name="NodeType">
														<xsl:value-of select="'Field'"/>
													</xsl:attribute>
												</ID>
												<TextTranslation>
													<xsl:for-each select="$E1MTXHM/SPRAS_ISO">
														<xsl:variable name="SPRAS_ISO4" select="."/>
														<xsl:variable name="SAPLanguageIDConversionResult4">
															<xsl:call-template name="SAPLanguageIDConversion">
																<xsl:with-param name="SPRAS_ISO" select="$SPRAS_ISO4"/>
															</xsl:call-template>
														</xsl:variable>
														<LanguageID>
															<xsl:value-of select="$SAPLanguageIDConversionResult4"/>
														</LanguageID>
													</xsl:for-each>
													<xsl:for-each select="$E1MTXLM/TDLINE">
														<xsl:variable name="TDLINE" select="."/>
														<xsl:for-each select="$E1MTXHM/TDOBJECT">
															<xsl:variable name="TDOBJECT1" select="."/>
															<xsl:variable name="ComparisonResult25" select="$TDOBJECT1 = 'MATERIAL'"/>
															<xsl:if test="string($ComparisonResult25)='true'">
																<Extended>
																	<xsl:value-of select="$TDLINE"/>
																</Extended>
															</xsl:if>
														</xsl:for-each>
													</xsl:for-each>
													<TextID>
														<xsl:attribute name="NodeType">
															<xsl:value-of select="'Field'"/>
														</xsl:attribute>
													</TextID>
												</TextTranslation>
											</Product_Text>
										</xsl:if>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</Product>
				</xsl:for-each>
			</xsl:for-each>
		</FlexNet_Products>
	</xsl:template>
</xsl:stylesheet>
